dist: xenial

language: python

python:
- 3.5
- 3.6
- 3.7
- 3.8

install:
- pip install -r requirements.txt

git:
  depth: 3

branches:       # since the master branch is the only one where PRs are
  only:         # merged in.
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/    # for release tags

script:
- pytest
- mypy ./ || true

deploy:         # deploy to PyPI on tagged commits.
  provider: pypi
  user: N-Wouda
  password:
    secure: jEir1QB2CIAfTeJZU2DXtHBSQj2TAZx6fTkONbAsN7a8KAm0edhgkiYqly9+M3wmnFTr1Q+ycjbuStCkgreC7AOYwpQLi8BjVdm13SVpGCkVXX6hK/AW+J+WWlBZfg8TxNYBauPVJBIFyEuU6NqGxqrLHu3u+DVaIvBHNgTCMixClvODwhwA0P3o1XJTe0dCZWZHGtyHUpzx1N2oSCOOtCZJJfiFOPAWV5efWe04c5n6ymUOiq3WeNydJmrpRswaA2IH2AhFRjTdyVzYEbke5P+WkwXj/Kw4tU9pyyUtMMAbZODkCZn40KUnlr37HyQ2egsGWJ5J5B93pEJg/6QZneIwFFCsXwTJqKeCKojCD6zcTvlwqfINs75xR9L20Hce0evg8RckSRy1cw8s8wEpS89JPPlj03kq5Huu4BFkiYHojSzVJXRqPFBrkx2ao66US5zvCvg9I4WTkTQ/3gWptgI+r4gM1qdeWp5PFr0irVSjUgCQ43d3zkCEtPxAte2RVr6QoIxjMAEgwSle83eqdl67QYMMb4dpdbkQHoJPFh5Sn80dEPYXyOPSVnPbHEgX1GtXnI5cMY20G7TiRxutXag24CNWdMjj6sAZhiym2zWFca2fjaUApv+JRRIZ2GsZ0GqHXmE948Fe0gH0UCLRs6FmYiQwptKUCeGfjvCm+6Q=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true

after_success:
- codecov
